apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if eq .Values.frontend.service.type "NodePort" }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      nodePort: {{ .Values.frontend.service.nodePort }}
  {{- else }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-frontend