{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    {{- include "student-crud.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ .Values.monitoring.grafana.service.nodePort }}
  selector:
    {{- include "student-crud.labels" . | nindent 4 }}
{{- end }}