{{- if .Values.monitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus-server
  labels:
    {{- include "student-crud.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "student-crud.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "student-crud.labels" . | nindent 8 }}
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.monitoring.prometheus.image.repository }}:{{ .Values.monitoring.prometheus.image.tag }}
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-prometheus-config
{{- end }}