{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-server
  labels:
    {{- include "student-crud.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: {{ .Values.monitoring.prometheus.service.nodePort }}
  selector:
    {{- include "student-crud.labels" . | nindent 4 }}
{{- end }}