{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
  labels:
    {{- include "student-crud.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'student-crud-backend'
        static_configs:
          - targets: ['{{ .Release.Name }}-backend:3000']
      - job_name: 'student-crud-frontend'
        static_configs:
          - targets: ['{{ .Release.Name }}-frontend:80']
{{- end }}