apiVersion: v2
name: student-crud
description: A Student CRUD application with Kubernetes
version: 0.1.0
appVersion: "1.0.0"

_helpers.tpl: |
  {{- define "student-crud.fullname" -}}
  {{- printf "%s" .Release.Name | trunc 63 | trimSuffix "-" -}}
  {{- end -}}

  {{- define "student-crud.labels" -}}
  helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  app.kubernetes.io/name: {{ .Chart.Name }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  {{- end -}}