replicaCount: 2

backend:
  image:
    repository: student-crud-backend
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    port: 3000
    targetPort: 3000

frontend:
  image:
    repository: student-crud-frontend
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    port: 80
    nodePort: 30080

mongodb:
  enabled: true
  image:
    repository: mongo
    tag: 4.4
  auth:
    rootUser: admin
    rootPassword: password
  persistence:
    enabled: true
    size: 1Gi

monitoring:
  enabled: true
  
  grafana:
    image:
      repository: grafana/grafana
      tag: 9.5.3
    service:
      type: NodePort
      port: 3000
      nodePort: 30300
  
  prometheus:
    image:
      repository: prom/prometheus
      tag: v2.47.0
    service:
      type: NodePort
      port: 9090
      nodePort: 30900