name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-backend:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --health-cmd "mongosh --eval 'db.serverStatus()'" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - working-directory: ./backend
      run: npm ci
    - working-directory: ./backend
      run: npm test
      env:
        NODE_ENV: test

  build-test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - working-directory: ./frontend
      run: npm ci
    - working-directory: ./frontend
      run: npm test

  build-docker-images:
    needs: [build-test-backend, build-test-frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push backend
      run: |
        cd backend
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/estudiantes-crud-backend:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/estudiantes-crud-backend:latest
    
    - name: Build and push frontend
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/estudiantes-crud-frontend:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/estudiantes-crud-frontend:latest

  deploy-to-kubernetes:
    needs: build-docker-images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Install Helm
      uses: azure/setup-helm@v1
    
    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install estudiantes-crud ./helm/estudiantes-crud \
          --set backend.image.repository=${{ secrets.DOCKER_HUB_USERNAME }}/estudiantes-crud-backend \
          --set frontend.image.repository=${{ secrets.DOCKER_HUB_USERNAME }}/estudiantes-crud-frontend